spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hiramchatsystem?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=CTT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root